name: restaurant_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  extended_nested_scroll_view: ^5.1.3
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_sticky_header: ^0.6.4
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
