name: restaurant_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  android_alarm_manager_plus: ^2.0.7
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  extended_nested_scroll_view: ^5.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^11.0.1
  flutter_rating_bar: ^4.0.1
  flutter_sticky_header: ^0.6.4
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0-dev.3
  intl: ^0.17.0
  isar: ^3.0.1
  isar_flutter_libs: ^3.0.1
  json_annotation: ^4.6.0
  meta: ^1.8.0
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  sliver_tools: ^0.2.8

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.1
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
